add initd

diff --git a/lib/support/init.d/qmobile b/lib/support/init.d/qmobile
--- a/lib/support/init.d/qmobile
+++ b/lib/support/init.d/qmobile
@@ -5,13 +5,13 @@
 # Authors: icyleaf.cn@gmail.com
 
 ### BEGIN INIT INFO
-# Provides:          mobile
+# Provides:          qmobile
 # Required-Start:    $local_fs $remote_fs $network $syslog redis-server
 # Required-Stop:     $local_fs $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Mobile app management
-# Description:       Mobile app management
+# Short-Description: QMobile management
+# Description:       QMobile management
 # chkconfig: - 85 14
 ### END INIT INFO
 
@@ -34,14 +34,14 @@ app_root="/home/$app_user/www/mobile/current"
 pid_path="$app_root/tmp/pids"
 socket_path="$app_root/tmp/sockets"
 
-rails_socket="$socket_path/mobile.socket"
+rails_socket="$socket_path/puma.socket"
 
 web_server_pid_path="$pid_path/puma.pid"
-sidekiq_pid_path="$pid_path/sidekiq.pid"
+sidekiq_pid_path="$pid_path/sidekiq-0.pid"
 shell_path="/bin/bash"
 
 # Read configuration variable file if it is present
-test -f /etc/default/mobile && . /etc/default/mobile
+test -f /etc/default/qmobile && . /etc/default/qmobile
 
 # Switch to the app_user if it is not he/she who is running the script.
 if [ `whoami` != "$app_user" ]; then
@@ -62,7 +62,7 @@ check_pids(){
     echo "Could not create the path $pid_path needed to store the pids."
     exit 1
   fi
-  # If there exists a file which should hold the value of the Unicorn pid: read it.
+  # If there exists a file which should hold the value of the Puma pid: read it.
   if [ -f "$web_server_pid_path" ]; then
     wpid=$(cat "$web_server_pid_path")
   else
@@ -135,7 +135,7 @@ check_stale_pids(){
   # If there is a pid it is something else than 0, the service is running if
   # *_status is == 0.
   if [ "$wpid" != "0" ] && [ "$web_status" != "0" ]; then
-    echo "Removing stale Unicorn web server pid. This is most likely caused by the web server crashing the last time it ran."
+    echo "Removing stale Puma web server pid. This is most likely caused by the web server crashing the last time it ran."
     if ! rm "$web_server_pid_path"; then
       echo "Unable to remove stale pid, exiting."
       exit 1
@@ -154,25 +154,25 @@ check_stale_pids(){
 exit_if_not_running(){
   check_stale_pids
   if [ "$web_status" != "0" ] && [ "$sidekiq_status" != "0" ]; }; then
-    echo "GitLab is not running."
+    echo "QMobile is not running."
     exit
   fi
 }
 
-## Starts Unicorn and Sidekiq if they're not running.
-start_mobile() {
+## Starts Puma and Sidekiq if they're not running.
+start_qmobile() {
   check_stale_pids
 
   if [ "$web_status" != "0" ]; then
-    echo "Starting GitLab Unicorn"
+    echo "Starting QMobile Puma"
   fi
   if [ "$sidekiq_status" != "0" ]; then
-    echo "Starting GitLab Sidekiq"
+    echo "Starting QMobile Sidekiq"
   fi
 
   # Then check if the service is running. If it is: don't start again.
   if [ "$web_status" = "0" ]; then
-    echo "The Unicorn web server already running with pid $wpid, not restarting."
+    echo "The Puma web server already running with pid $wpid, not restarting."
   else
     # Remove old socket if it exists
     rm -f "$rails_socket" 2>/dev/null
@@ -189,20 +189,20 @@ start_mobile() {
 
   # Wait for the pids to be planted
   wait_for_pids
-  # Finally check the status to tell wether or not GitLab is running
+  # Finally check the status to tell wether or not QMobile is running
   print_status
 }
 
-## Asks Unicorn, Sidekiq and MailRoom if they would be so kind as to stop, if not kills them.
-stop_mobile() {
+## Asks Puma, Sidekiq and MailRoom if they would be so kind as to stop, if not kills them.
+stop_qmobile() {
   exit_if_not_running
 
   if [ "$web_status" = "0" ]; then
-    echo "Shutting down GitLab Unicorn"
+    echo "Shutting down QMobile Puma"
     RAILS_ENV=$RAILS_ENV bin/web stop
   fi
   if [ "$sidekiq_status" = "0" ]; then
-    echo "Shutting down GitLab Sidekiq"
+    echo "Shutting down QMobile Sidekiq"
     RAILS_ENV=$RAILS_ENV bin/background_jobs stop
   fi
 
@@ -225,54 +225,54 @@ stop_mobile() {
   print_status
 }
 
-## Prints the status of GitLab and its components.
+## Prints the status of QMobile and its components.
 print_status() {
   check_status
   if [ "$web_status" != "0" ] && [ "$sidekiq_status" != "0" ]; }; then
-    echo "GitLab is not running."
+    echo "QMobile is not running."
     return
   fi
   if [ "$web_status" = "0" ]; then
-      echo "The GitLab Unicorn web server with pid $wpid is running."
+      echo "The QMobile Puma web server with pid $wpid is running."
   else
-      printf "The GitLab Unicorn web server is \033[31mnot running\033[0m.\n"
+      printf "The QMobile Puma web server is \033[31mnot running\033[0m.\n"
   fi
   if [ "$sidekiq_status" = "0" ]; then
-      echo "The GitLab Sidekiq job dispatcher with pid $spid is running."
+      echo "The QMobile Sidekiq job dispatcher with pid $spid is running."
   else
-      printf "The GitLab Sidekiq job dispatcher is \033[31mnot running\033[0m.\n"
+      printf "The QMobile Sidekiq job dispatcher is \033[31mnot running\033[0m.\n"
   fi
 
   if [ "$web_status" = "0" ] && [ "$sidekiq_status" = "0" ]; }; then
-    printf "GitLab and all its components are \033[32mup and running\033[0m.\n"
+    printf "QMobile and all its components are \033[32mup and running\033[0m.\n"
   fi
 }
 
-## Tells unicorn to reload its config and Sidekiq to restart
+## Tells puma to reload its config and Sidekiq to restart
 reload_mobile(){
   exit_if_not_running
   if [ "$wpid" = "0" ];then
-    echo "The GitLab Unicorn Web server is not running thus its configuration can't be reloaded."
+    echo "The QMobile Puma Web server is not running thus its configuration can't be reloaded."
     exit 1
   fi
-  printf "Reloading GitLab Unicorn configuration... "
+  printf "Reloading QMobile Puma configuration... "
   RAILS_ENV=$RAILS_ENV bin/web reload
   echo "Done."
 
-  echo "Restarting GitLab Sidekiq since it isn't capable of reloading its config..."
+  echo "Restarting QMobile Sidekiq since it isn't capable of reloading its config..."
   RAILS_ENV=$RAILS_ENV bin/background_jobs restart
 
   wait_for_pids
   print_status
 }
 
-## Restarts Sidekiq and Unicorn.
-restart_mobile(){
+## Restarts Sidekiq and Puma.
+restart_qmobile(){
   check_status
   if [ "$web_status" = "0" ] || [ "$sidekiq_status" = "0" ]; }; then
-    stop_mobile
+    stop_qmobile
   fi
-  start_mobile
+  start_qmobile
 }
 
 
@@ -280,23 +280,23 @@ restart_mobile(){
 
 case "$1" in
   start)
-        start_mobile
+        start_qmobile
         ;;
   stop)
-        stop_mobile
+        stop_qmobile
         ;;
   restart)
-        restart_mobile
+        restart_qmobile
         ;;
   reload|force-reload)
 	reload_mobile
         ;;
   status)
         print_status
-        exit $mobile_status
+        exit $qmobile_status
         ;;
   *)
-        echo "Usage: service mobile {start|stop|restart|reload|status}"
+        echo "Usage: service qmobile {start|stop|restart|reload|status}"
         exit 1
         ;;
 esac
